<#
事前に決定したスペシャルフォルダのエイリアスを指定
変更が必要な場合は、管理者と話し合うこと。
#>
$TargetAlias = @(
    "MyDocuments"
    "DesktopDirectory"
    "CommonDesktopDirectory"
    "Favorites"
    "MyMusic"
    "MyVideos"
    "MyPictures"
    "Download"
    # "Desktop"
    # "UserProfile"
    # "Programs"
    # "Personal"
    # "Startup"
    # "Recent"
    # "SendTo"
    # "StartMenu"
    # "MyComputer"
    # "NetworkShortcuts"
    # "Fonts"
    # "Templates"
    # "CommonStartMenu"
    # "CommonPrograms"
    # "CommonStartup"
    # "ApplicationData"
    # "PrinterShortcuts"
    # "LocalApplicationData"
    # "InternetCache"
    # "Cookies"
    # "History"
    # "CommonApplicationData"
    # "Windows"
    # "System"
    # "ProgramFiles"
    # "SystemX86"
    # "ProgramFilesX86"
    # "CommonProgramFiles"
    # "CommonProgramFilesX86"
    # "CommonTemplates"
    # "CommonDocuments"
    # "CommonAdminTools"
    # "AdminTools"
    # "CommonMusic"
    # "CommonPictures"
    # "CommonVideos"
    # "Resources"
    # "LocalizedResources"
    # "CommonOemLinks"
    # "CDBurning"
)
